Tipsy react native web
marmelab/tipsy-isomorph pull request #2
Opened 2021-02-15 14:21 UTC by guilbill

## Description

Add the possibility to play on the same browser with an opponent.
![Peek 15-02-2021 15-11](https://user-images.githubusercontent.com/560852/107957768-5fa50480-6fa1-11eb-8265-2a1263f806da.gif)

## ToDo list:

- [x] use react native web to reuse components from mobile project
- [x] adapt a little components to allow playing in the same browser

2021-02-15 14:43 UTC, djhi commented on pages/api/GameApi.jsx
> +const gameApi = {
Why do we need this? Why aren't we calling the symfony API directly from the client app? Or am I missing something?

2021-02-15 16:02 UTC, djhi requested changes

2021-02-15 16:02 UTC, djhi commented on lib/game/GameStatus.jsx
> +    }, [game.players]);
Why do you memoize that? Is it expensive?

2021-02-15 16:02 UTC, djhi commented on lib/game/api/GameApi.jsx
> +import CONSTANTS from "../../../const";
That's better. Why placing this file in such a deep directory? You're planning to have so many thing in `lib`?

2021-02-15 16:02 UTC, djhi commented on pages/index.js
> +            <Game></Game>
```suggestion
            <Game />
```
Unless you plan to have children later?

2021-02-15 16:19 UTC, guilbill commented on lib/game/GameStatus.jsx
> +    }, [game.players]);
It's not very expensive, but it will not change, unless game.players changes... So I though it was relevant to memoize that. You think it's overkill?

2021-02-15 16:41 UTC, djhi commented on lib/game/GameStatus.jsx
> +    }, [game.players]);
Memoizing has a memory cost so unless you really have a reason to memoize, don't.

2021-02-15 16:42 UTC, djhi commented on lib/game/api/GameApi.jsx
> +import CONSTANTS from "../../../const";
Sorry it wasn't clear, I was referring to the GameApi file.

2021-02-16 09:00 UTC, djhi approved these changes

2021-02-16 09:00 UTC, merged